apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: release-platform-rollout
  namespace: default
  labels:
    app: release-platform
  annotations:
    notifications.argoproj.io/subscribe.on-rollout-updated.slack_webhook: ""
    notifications.argoproj.io/subscribe.on-rollout-step-completed.slack_webhook: ""
    notifications.argoproj.io/subscribe.on-analysis-run-failed.slack_webhook: ""
    notifications.argoproj.io/subscribe.on-rollout-aborted.slack_webhook: ""
    notifications.argoproj.io/subscribe.on-rollout-completed.slack_webhook: ""

spec:
  replicas: 4

  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: release-platform

  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: release-platform
    scaleDown: never

  strategy:
    canary:
      maxSurge: 1
      maxUnavailable: 0

      steps:
        - setWeight: 25

        - pause:
            duration: 30s

        - analysis:
            templates:
              - templateName: release-platform-health

        - setWeight: 50

        - pause:
            duration: 30s

        - analysis:
            templates:
              - templateName: release-platform-health

        - setWeight: 75

        - pause:
            duration: 30s

        - analysis:
            templates:
              - templateName: release-platform-health