apiVersion: apps/v1
kind: Deployment

metadata:
  name: release-platform

spec:
  replicas: 0

  selector:
    matchLabels:
      app: release-platform

    spec:
      template:
        metadata:
          labels:
            app: release-platform
          annotations:

    spec:
      containers:
        - name: release-platform
          image: ghcr.io/rohannsaxena2609/autonomous-release-platform:5d8af29fd541e798a1a05847a8ab8d59e78c43b5
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080

          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: release-platform-config
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: release-platform-config
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: release-platform-secret
                  key: SPRING_DATASOURCE_PASSWORD

          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 60

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5

          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"

            limits:
              memory: "512Mi"
              cpu: "750m"
