apiVersion: apps/v1
kind: Deployment

metadata:
  name: release-platform

spec:
  replicas: 2

  selector:
    matchLabels:
      app: release-platform

  template:
    metadata:
      labels:
        app: release-platform

    spec:
      containers:
        - name: release-platform
          image: ghcr.io/rohannsaxena2609/autonomous-release-platform:7634988c06f841a17308190648d293e121b3b2ee
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080

          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: release-platform-config
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: release-platform-config
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: release-platform-secret
                  key: SPRING_DATASOURCE_PASSWORD

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"

            limits:
              memory: "512Mi"
              cpu: "750m"
